# paasta-sourcecontrol-service 설정 파일 내용
name: paasta-sourcecontrol-service                      # 서비스 배포이름(필수)

releases:
- name: paasta-sourcecontrol-release                    # 서비스 릴리즈 이름(필수)
  version: "latest"                                        # 서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

update:
  canaries: 1                            # canary 인스턴스 수(필수)
  canary_watch_time: 30000-120000        # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 4                       # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  update_watch_time: 30000-120000        # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)

instance_groups:
- name: scm-server
  azs:
  - z3
  instances: 1
  persistent_disk_type: 30GB
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((default_network_name))
    static_ips:
    - 10.0.81.21
  jobs:
  - name: scm-server
    release: paasta-sourcecontrol-release

- name: mariadb
  azs:
  - z3
  instances: 1
  persistent_disk_type: 2GB
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((default_network_name))
    static_ips:
    - 10.0.81.22
  jobs:
  - name: mariadb
    release: paasta-sourcecontrol-release

- name: haproxy
  azs:
  - z7
  instances: 1
  persistent_disk_type: 2GB
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((default_network_name))
    static_ips:
    - 10.0.0.103
  - name: ((public_network_name))
    static_ips:
    - [HAPROXY_EXTERNAL_IP]
  jobs:
  - name: haproxy
    release: paasta-sourcecontrol-release

- name: sourcecontrol-webui
  azs:
  - z3
  instances: 1
  persistent_disk_type: 2GB
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((default_network_name))
    static_ips:
    - 10.0.81.24
  jobs:
  - name: sourcecontrol-webui
    release: paasta-sourcecontrol-release

- name: sourcecontrol-api
  azs:
  - z3
  instances: 1
  persistent_disk_type: 2GB
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((default_network_name))
    static_ips:
    - 10.0.81.25
  jobs:
  - name: sourcecontrol-api
    release: paasta-sourcecontrol-release

- name: sourcecontrol-broker
  azs:
  - z3
  instances: 1
  persistent_disk_type: 2GB
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((default_network_name))
    static_ips:
    - 10.0.81.26
  jobs:
  - name: sourcecontrol-broker
    release: paasta-sourcecontrol-release

properties:
  spring:
    datasource:
      url: jdbc:mysql://10.0.81.22:31306/PAASTA_SRC_DB?autoReconnect=true&useUnicode=true&characterEncoding=utf8
      username: sourcecontrol
      password: '!scadmin2017'
      databasename: "PAASTA_SRC_DB"
    jpa:
      database: mysql

  haproxy:                                # sourcecontrol haproxy
    host_ip: 10.0.0.103                # sourcecontrol haproxy host IP
    url: 10.0.0.103                # sourcecontrol haproxy host IP
    http_port: 8080                        # sourcecontrol haproxy host port

  sourcecontrol-webui:                  # sourcecontrol webui
    port: 8080
    haproxy:
      urls:
      - 10.0.81.24
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  sourcecontrol-api:                    # sourcecontrol api
    base:
      url: http://10.0.81.25:8082        # sourcecontrol api base url
    port: 8082                              # sourcecontrol api port
    haproxy:
      urls:
      - 10.0.81.25
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  sourcecontrol-broker:                 # sourcecontrol broker
    port: 8080                               # sourcecontrol port
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  mariadb:
    port: 31306
    datasource:
      username: root
      password: "!paas_ta202"
      databasename:  "PAASTA_SRC_DB"

  scm:
    base:
      url: http://10.0.81.21:8084/scm
      port: 8084
    haproxy:
      urls:
      - 10.0.81.21
    clone:
      url: http://[HAPROXY_EXTERNAL_IP]:8084/scm
  dashboard:
    url: http://[HAPROXY_EXTERNAL_IP]:8080/repositories/user/{instanceId}
  api:
    user: '/api/rest/users'
    repo: '/api/rest/repositories'
  cf:
    uaa:
      oauth:
        info:
          uri: https://uaa.xxx.xxx.xxx.xxx.xip.io/userinfo
        token:
          check:
            uri: https://uaa.xxx.xxx.xxx.xxx.xip.io/check_token
          access:
            uri: https://uaa.xxx.xxx.xxx.xxx.xip.io/oauth/token
        logout:
          url: https://uaa.xxx.xxx.xxx.xxx.xip.io/logout.do
        authorization:
          uri: https://uaa.xxx.xxx.xxx.xxx.xip.io/oauth/authorize
        client:
          id: scclient
          secret: clientsecret
    api:
      url: https://api.xxx.xxx.xxx.xxx.xip.io/v2/service_instances/[SUID]/permissions

