---
name: paasta-sourcecontrol-release                               # 서비스 배포이름(필수) bosh deployments 로 확인가능한 이름
director_uuid: <%= `bosh status --uuid` %>     # Director UUID을 입력(필수) bosh status 명령으로 확인가능
  
compilation:                                            # 컴파일시 필요한 가상머신의 속성(필수)
  workers: 4                                             # 컴파일 하는 가상머신의 최대수(필수)
  network: default                                       # Networks block에서 선언한 network 이름(필수)
  reuse_compilation_vms: true
  max_in_flight: 1                                          # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  serial: false  
  
  cloud_properties:                                    # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성 (instance_type, availability_zone), 직접 cpu,disk,ram 사이즈를 넣어도 됨
    ram: 2048
    disk: 8096
    cpu: 2
  
# this section describes how updates are handled
update:
  canaries: 1                                    # canary 인스턴스 수(필수)
  canary_watch_time: 5000-120000                    # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 5000-120000                    # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 4                              # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  serial: false                                 # 순차적으로 업데이트 함. 
networks:
- name: default               # 네트워크 블록에 나열된 각 서브 블록이 참조 할 수있는 작업이 네트워크 구성을 지정, 네트워크 구성은 네트워크 담당자에게 문의 하여 작성 요망
  subnets:
  - cloud_properties:
      name: Internal          # vsphere 에서 사용하는 network 이름(필수)
    dns:                      # DNS 정보
    - 10.30.20.24
    - 8.8.8.8
    gateway: 10.30.20.23
    name: default_unused
    range: 10.30.0.0/16
    reserved:                 # 설치시 제외할 IP 설정
    - 10.30.20.0 - 10.30.20.22
    - 10.30.40.0 - 10.30.40.255
    - 10.30.60.0 - 10.30.60.122
    static:
    - 10.30.120.0 - 10.30.130.255           #사용 가능한 IP 설정
- name: op_public_network
  type: manual
  subnets:
  - cloud_properties:
      name: External
    dns:
    - 8.8.8.8
    gateway: 115.68.46.177
    range: 115.68.46.176/28
    static:
    - 115.68.46.188
  
- name: op_public_network1
  type: manual
  subnets:
  - cloud_properties:
      name: External
    dns:
    - 8.8.8.8
    gateway: 115.68.46.209
    range: 115.68.46.208/28
    static:
    - 115.68.46.214
  
resource_pools:               # 배포시 사용하는 resource pools를 명시하며 여러 개의 resource pools 을 사용할 경우 name 은 unique 해야함(필수)
- name: first_pools      # 고유한 resource pool 이름
  network: default
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: "3421.4"
  director:
    enable_post_deploy: true
  cloud_properties:
    cpu: 1
    disk: 8192
    ram: 1024
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  
- name: second_pools      # 고유한 resource pool 이름
  network: default
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: "3421.4"
  cloud_properties:
    cpu: 1
    disk: 8192
    ram: 2048
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  
- name: third_pools      # 고유한 resource pool 이름
  network: default
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: "3421.4"
  cloud_properties:
    cpu: 2
    disk: 8192
    ram: 2048
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  
- name: four_pools      # 고유한 resource pool 이름
  network: default
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: "3421.4"
  cloud_properties:
    cpu: 1
    disk: 8192
    ram: 4096
    enable_post_deploy: true
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  
jobs:
- name: scm-server
  instances: 1
  resource_pool: four_pools          # resource_pools block에 정의한 resource pool 이름(필수)
  persistent_disk: 30720                 # 영구적 디스크 사이즈 정의(옵션)
  networks:                              # 네트워크 구성정보
  - name: default                        # Networks block에서 선언한 network 이름(필수) 내부 네트워크 설정
    static_ips:
    - 10.30.120.121                      # 사용할 내부 IP addresses 정의(필수)
  templates:
  - name: scm-server
    release: paasta-sourcecontrol-release
  update:
    max_in_flight: 1
    serial: true
  
- name: mariadb
  instances: 1                    # job ÀÎ½ºÅÏ½º ¼ö(ÇÊ¼ö)
  resource_pool: third_pools      # resource_pools block¿¡ Á¤ÀÇÇÑ resource pool ÀÌ¸§(ÇÊ¼ö)
  persistent_disk: 2048
  networks:
  - name: default                 # Networks block
    static_ips:
    - 10.30.120.122
  templates:
  - name: mariadb
    release: paasta-sourcecontrol-release
  update:
    max_in_flight: 1
    serial: true
 
- name: haproxy
  instances: 1
  resource_pool: first_pools           # resource_pools block
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 10.30.120.123
  - name: op_public_network    # Public network 설정
    default: [dns, gateway]
    static_ips: 115.68.46.188  # change it!
  templates:
  - name: haproxy
    release: paasta-sourcecontrol-release
  update:
    max_in_flight: 1
    serial: true
  
- name: sourcecontrol-webui
  instances: 1
  resource_pool: second_pools
  persistent_disk: 2048
  networks:
  - name: default
    static_ips: 
    - 10.30.120.124
  templates:
  - name: sourcecontrol-webui
    release: paasta-sourcecontrol-release
  update:
    max_in_flight: 1
    serial: true
  
- name: sourcecontrol-api
  instances: 1
  resource_pool: second_pools
  persistent_disk: 2048
  networks: 
  - name: default
    static_ips:
    - 10.30.120.125
  templates:
  - name: sourcecontrol-api
    release: paasta-sourcecontrol-release
  update:
    max_in_flight: 1
    serial: false
 
- name: sourcecontrol-broker
  instances: 1
  resource_pool: second_pools
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 10.30.120.126
  templates:
  - name: sourcecontrol-broker
    release: paasta-sourcecontrol-release
  update:
    max_in_flight: 1
    serial: false
  
properties:
  spring:
    datasource:
      url: jdbc:mysql://10.30.120.122:31306/PAASTA_SRC_DB?autoReconnect=true&useUnicode=true&characterEncoding=utf8
      username: sourcecontrol
      password: '!scadmin2017'
      databasename: "PAASTA_SRC_DB"
    jpa:
      database: mysql
  
  haproxy:                                # sourcecontrol haproxy
    host_ip: 10.30.120.123                # sourcecontrol haproxy host IP
    url: 10.30.120.123                # sourcecontrol haproxy host IP
    http_port: 8080                        # sourcecontrol haproxy host port
  
  sourcecontrol-webui:                  # sourcecontrol webui
    port: 8080
    haproxy:
      urls:
      - 10.30.120.124
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'
  
  sourcecontrol-api:                    # sourcecontrol api
    base:
      url: http://10.30.120.125:8082        # sourcecontrol api base url
    port: 8082                              # sourcecontrol api port
    haproxy:
      urls:
      - 10.30.120.125
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'
  
  sourcecontrol-broker:                 # sourcecontrol broker
    port: 8080                               # sourcecontrol port
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'
  
  mariadb:
    port: 31306
    datasource:
      username: root
      password: "!paas_ta202"
      databasename:  "PAASTA_SRC_DB"
  
  scm:
    base:
      url: http://10.30.120.121:8084/scm
      port: 8084
    haproxy:
      urls:
      - 10.30.120.121
    clone:
      url: http://115.68.46.188:8084/scm
  dashboard:
    url: http://115.68.46.188:8080/repositories/user/{instanceId}
  api:
    user: '/api/rest/users'
    repo: '/api/rest/repositories'
  cf:
    uaa:
      oauth:
        info:
          uri: https://uaa.115.68.46.187.xip.io/userinfo
        token:
          check:
            uri: https://uaa.115.68.46.187.xip.io/check_token
          access:
            uri: https://uaa.115.68.46.187.xip.io/oauth/token
        logout:
          url: https://uaa.115.68.46.187.xip.io/logout.do
        authorization:
          uri: https://uaa.115.68.46.187.xip.io/oauth/authorize
        client:
          id: scclient
          secret: clientsecret
    api:
      url: https://api.115.68.46.187.xip.io/v2/service_instances/[SUID]/permissions
  
releases:
- name: paasta-sourcecontrol-release
  version: 1.0
